name: Keep Streamlit Alive

on:
  schedule:
    - cron: "*/30 * * * *"  # runs every 10 minutes
  workflow_dispatch:        # allows you to trigger manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: curl -s https://your-app.streamlit.app > /dev/null
